### ISSUE TITLE
As a observer of the MSF-Delegates page, I need a clear README so that I know when you meet, and how I can get involved. 

### ISSUE THREAD

**Issue by mrmetaverse** [omigroup/MSF-Delegates#1]
The MSF README should be a plain-language document that says: 

- [x] here is when/how often we meet! 
- [x] here is a link to our working agreement if we have one (it says when we meet, how we track work, how we handle conflict or how often we want to have a retro) 
- [x] here is a link to our backlog if we have one (not every group needs a backlog, but if you want to track known items a repo backlog syncs directly with an org-level backlog, and it makes it easier for me (Jesse) to help you track your tickets!) 
- [x] in general: here is how you can get involved! 

Groups are different skill sets, different time zones, and availabilities. Therefore, each group sets their own meeting time/cadence and decides on how they want to track work. It is at the group level that these are defined because we are all volunteers.

**Comment by funksoup** [comment]
include vision statement
refine vision statement & scope of work via [Miro board](https://miro.com/welcomeonboard/d2w2cHR0VlY3N2ZKakpoeURaSXJJaWYzTjVmejM0Rnk2RzJiVWx0Z25STU1UOG1oRkRzNkdLejNsOERPMzNGcHwzNDU4NzY0NTMxMzY4NzMwNjIy?share_link_id=365578964555)
include exploratory group proposal links

**Comment by funksoup** [comment]
https://github.com/omigroup/MSF-Delegates/issues/12 is a duplicate - closing it

**Comment by pcsmgnt** [comment]
I found a few minutes to take a stab at the draft for review.

**Comment by funksoup** [comment]
Added draft of scope of work to repo (Scope_of_Work.md). Small edits to README.

**Comment by mrmetaverse** [comment]
Your readme looks great! I think we can move this to "done" at least for a baseline. You can always continue to thread updates in this ticket even beyond done, and you can always create new tickets for tweaks or changes that need to be reviewed. I will leave the ceremonious "Close with Comment" to you. 

Note: When you close a ticket, it automatically moves to "done" on your kanban board.

**Comment by fire** [comment]
This appears to be done.

**Comment by pcsmgnt** [comment]
I agree. I suggested marking it as done, was told to keep it in draft status besides no further clear action regarding what is needed to get it to "done" status.

**Comment by humbletim** [comment]
> I agree. I suggested marking it as done, was told to keep it in draft status besides no further clear action regarding what is needed to get it to "done" status.

it's a great readme.. please consider removing my name from the document. this is a sincere and simple suggestion to unblock this ticket.

**Comment by mrmetaverse** [comment]
Done
