### ISSUE TITLE
Feedback poll results of domain interests

### ISSUE THREAD

**Issue by pcsmgnt** [omigroup/MSF-Delegates#11]

**Comment by humbletim** [comment]
related to populating / tallying in the MSF brainstorming spreadsheet email columns:
(reference: ![image](https://user-images.githubusercontent.com/94753/190197815-dc745157-ac20-424c-9ca5-49cfb700bcc7.png))

**Comment by humbletim** [comment]
re: discord poll: https://discord.com/channels/770382203782692945/976535598313644113/1004443257343856801

**Comment by pcsmgnt** [comment]
Poll Results are:

:regional_indicator_b: Interoperable 3D Assets
:regional_indicator_e: User Identity and Login
:regional_indicator_i: Runtimes and Object Model
:regional_indicator_a: Metaverse Standards Registry
:regional_indicator_j: Networking
