### ISSUE TITLE
Complete MSF Delegates Repo Readme

### ISSUE THREAD

**Issue by pcsmgnt** [omigroup/MSF-Delegates#12]

**Comment by funksoup** [comment]
include vision statement
refine vision statement & scope of work via [Miro board](https://miro.com/welcomeonboard/d2w2cHR0VlY3N2ZKakpoeURaSXJJaWYzTjVmejM0Rnk2RzJiVWx0Z25STU1UOG1oRkRzNkdLejNsOERPMzNGcHwzNDU4NzY0NTMxMzY4NzMwNjIy?share_link_id=365578964555)
include exploratory group proposal links

**Comment by funksoup** [comment]
This is a duplicate - closing it. Refer to https://github.com/omigroup/MSF-Delegates/issues/1 instead.
