### ISSUE TITLE
Look into github kanban functionality & extensions (Jesse)

### ISSUE THREAD

**Issue by funksoup** [omigroup/MSF-Delegates#15]

**Comment by funksoup** [comment]
Jesse to give a brief tutorial on github repo project tips and tricks next week, Wed, 7 Sept, 15:30 UTC.

**Comment by mrmetaverse** [comment]
> Jesse to give a brief tutorial on github repo project tips and tricks next week, Wed, 7 Sept, 15:30 UTC.

See you then!

**Comment by funksoup** [comment]
Done - Thanks @mrmetaverse! [Notes here](https://github.com/omigroup/MSF-Delegates/discussions/16#discussioncomment-3586780)
