### ISSUE TITLE
As a member of the MSF delegates, I might need to know where to put to-do's so that I can ensure we don't drop any balls or waste time with parallel work. 

### ISSUE THREAD

**Issue by mrmetaverse** [omigroup/MSF-Delegates#2]
- Do we want a backlog? 
- If yes, how will we manage the backlog? Do we spend 5 min at the beginning of every meeting reviewing the in-flight tix and adding new ones from the backlog to the to-do? Or do we have one person track it all and assign? Or do we not want one at all?

**Comment by fire** [comment]
Is the status quo do put work here and in the discussions? Anything more to do?

**Comment by mrmetaverse** [comment]
There is a active backlog
