### ISSUE TITLE
As a MSF member I want github changes to sync with discord so that I don't miss anything important. 

### ISSUE THREAD

**Issue by mrmetaverse** [omigroup/MSF-Delegates#4]
Using a webhook, as we have with other repos, create a link between the github repo and the discord channel.

**Comment by mrmetaverse** [comment]
I didn't create a backlog because it is up to the group to decide on #2, but I am setting up the webhook now

**Comment by mrmetaverse** [comment]
test

**Comment by mrmetaverse** [comment]
Integration is complete, please see this milestone for the remaining items in your first milestone! https://github.com/omigroup/MSF-Delegates/milestone/1

**Comment by pcsmgnt** [comment]
Thank you @mrmetaverse
